export const heatMap =
{
    "data": [{
        "name": "诸海滨团队",
        "num": 705,
        "chg_ratio": 211.95
    }, {
        "name": "杨诚笑团队",
        "num": 503,
        "chg_ratio": 116.81
    }, {
        "name": "李佳团队",
        "num": 490,
        "chg_ratio": 172.22
    }, {
        "name": "陈显帆团队",
        "num": 384,
        "chg_ratio": 103.17
    }, {
        "name": "马莉团队",
        "num": 301,
        "chg_ratio": 89.31
    }, {
        "name": "鲍荣富团队",
        "num": 296,
        "chg_ratio": 51.02
    }, {
        "name": "申万环保公用",
        "num": 292,
        "chg_ratio": -2.67
    }, {
        "name": "沈娟团队",
        "num": 280,
        "chg_ratio": 73.91
    }, {
        "name": "邓永康团队",
        "num": 276,
        "chg_ratio": 29.58
    }, {
        "name": "天风机械",
        "num": 274,
        "chg_ratio": 79.08
    }, {
        "name": "申万轻工造纸团队",
        "num": 259,
        "chg_ratio": 45.51
    }, {
        "name": "焦娟团队",
        "num": 251,
        "chg_ratio": 156.12
    }, {
        "name": "兴证医药",
        "num": 247,
        "chg_ratio": 414.58
    }, {
        "name": "李斌团队",
        "num": 233,
        "chg_ratio": 119.81
    }, {
        "name": "马鲲鹏团队",
        "num": 226,
        "chg_ratio": 10.24
    }],
    "code": 200,
    "message": ""
}