package la.niub.abcapi.servicecompre.dao.reporter;


import la.niub.abcapi.servicecompre.model.Navigation_bar;
import org.apache.ibatis.annotations.Mapper;
import java.util.List;
import java.util.Map;


/**
* This code is generated by FreeMarker
* @author viq
*
*/
@Mapper
public interface INavigation_barDao {
    public int insert(Navigation_bar navigation_bar);
    public int delete(Navigation_bar navigation_bar);
    public int update(Navigation_bar navigation_bar);
    public List<Navigation_bar> find(Map paramMap);
	public int getCount(Map paramMap);
}