export const options = [
    {
        "type":"market",
        "item":[
            {
                "id":null,
                "name":"沪深股",
                "count":5961265
            },
            {
                "id":null,
                "name":"美股",
                "count":4491398
            },
            {
                "id":null,
                "name":"新三板",
                "count":1659284
            },
            {
                "id":null,
                "name":"港股",
                "count":1328773
            },
            {
                "id":null,
                "name":"基金",
                "count":823240
            },
            {
                "id":null,
                "name":"其他",
                "count":367173
            },
            {
                "id":null,
                "name":"债券",
                "count":355644
            }
        ],
        "id":-1,
        "showname":"市场",
        "multiValued":true
    },
    {
        "type":"industryIds",
        "item":[
            {
                "id":"2447",
                "name":"制造业",
                "count":795281
            },
            {
                "id":"2330",
                "name":"金融",
                "count":477737
            },
            {
                "id":"2372",
                "name":"信息技术",
                "count":438631
            },
            {
                "id":"2193",
                "name":"工业",
                "count":407817
            },
            {
                "id":"2311",
                "name":"医疗保健",
                "count":396876
            },
            {
                "id":"2236",
                "name":"非日常生活消费品",
                "count":379629
            },
            {
                "id":"1658",
                "name":"化工 ",
                "count":366430
            },
            {
                "id":"2503",
                "name":"信息传输、软件和信息技术服务业",
                "count":343588
            },
            {
                "id":"1878",
                "name":"医药生物",
                "count":339444
            },
            {
                "id":"1762",
                "name":"机械设备",
                "count":339085
            },
            {
                "id":"1916",
                "name":"电子",
                "count":263974
            },
            {
                "id":"1933",
                "name":"计算机",
                "count":248767
            },
            {
                "id":"1988",
                "name":"房地产",
                "count":247407
            },
            {
                "id":"1743",
                "name":"电气设备 ",
                "count":234908
            },
            {
                "id":"1958",
                "name":"公用事业",
                "count":225720
            },
            {
                "id":"2158",
                "name":"能源",
                "count":216600
            },
            {
                "id":"1939",
                "name":"传媒",
                "count":214044
            },
            {
                "id":"3040",
                "name":"消费品制造业",
                "count":203785
            },
            {
                "id":"2169",
                "name":"原材料",
                "count":189370
            },
            {
                "id":"1795",
                "name":"汽车",
                "count":175524
            },
            {
                "id":"1700",
                "name":"有色金属",
                "count":164882
            },
            {
                "id":"3113",
                "name":"地产建筑业",
                "count":160540
            },
            {
                "id":"1725",
                "name":"建筑装饰 ",
                "count":141434
            },
            {
                "id":"1971",
                "name":"交通运输",
                "count":136698
            },
            {
                "id":"1828",
                "name":"农林牧渔",
                "count":135183
            },
            {
                "id":"1816",
                "name":"轻工制造",
                "count":134387
            },
            {
                "id":"1892",
                "name":"商业贸易",
                "count":132096
            },
            {
                "id":"3070",
                "name":"消费者服务业",
                "count":129631
            },
            {
                "id":"1951",
                "name":"通信",
                "count":129140
            },
            {
                "id":"3024",
                "name":"工业",
                "count":124328
            },
            {
                "id":"2289",
                "name":"日常消费品",
                "count":119271
            },
            {
                "id":"3103",
                "name":"金融业",
                "count":117319
            },
            {
                "id":"2417",
                "name":"房地产",
                "count":108862
            },
            {
                "id":"1716",
                "name":"建筑材料 ",
                "count":98083
            },
            {
                "id":"1996",
                "name":"非银金融",
                "count":95295
            },
            {
                "id":"1850",
                "name":"食品饮料",
                "count":93430
            },
            {
                "id":"2404",
                "name":"公用事业",
                "count":93306
            },
            {
                "id":"1863",
                "name":"纺织服装",
                "count":91262
            },
            {
                "id":"1806",
                "name":"家用电器",
                "count":90196
            },
            {
                "id":"3124",
                "name":"资讯科技业",
                "count":89032
            },
            {
                "id":"1647",
                "name":"采掘",
                "count":80698
            },
            {
                "id":"2514",
                "name":"租赁和商务服务业",
                "count":78995
            },
            {
                "id":"3010",
                "name":"原材料业",
                "count":78718
            },
            {
                "id":"2517",
                "name":"科学研究和技术服务业",
                "count":71561
            },
            {
                "id":"2488",
                "name":"批发和零售业",
                "count":71436
            },
            {
                "id":"2003",
                "name":"综合",
                "count":67550
            },
            {
                "id":"1786",
                "name":"国防军工",
                "count":62446
            },
            {
                "id":"2483",
                "name":"建筑业",
                "count":59330
            },
            {
                "id":"1904",
                "name":"休闲服务",
                "count":52974
            },
            {
                "id":"1696",
                "name":"钢铁",
                "count":50266
            },
            {
                "id":"3002",
                "name":"能源业",
                "count":49671
            },
            {
                "id":"2534",
                "name":"文化、体育和娱乐业",
                "count":39623
            },
            {
                "id":"2397",
                "name":"电信业务",
                "count":37631
            },
            {
                "id":"2433",
                "name":"农、林、牧、渔业",
                "count":36255
            },
            {
                "id":"3097",
                "name":"公用事业",
                "count":36229
            },
            {
                "id":"2521",
                "name":"水利、环境和公共设施管理业",
                "count":34829
            },
            {
                "id":"2507",
                "name":"金融业",
                "count":25874
            },
            {
                "id":"2491",
                "name":"交通运输、仓储和邮政业",
                "count":25672
            },
            {
                "id":"1993",
                "name":"银行",
                "count":24119
            },
            {
                "id":"3134",
                "name":"综合企业",
                "count":19031
            },
            {
                "id":"2479",
                "name":"电力、热力、燃气及水生产和供应业",
                "count":17697
            },
            {
                "id":"2512",
                "name":"房地产业",
                "count":13143
            },
            {
                "id":"2529",
                "name":"教育",
                "count":12357
            },
            {
                "id":"3093",
                "name":"电讯业",
                "count":10618
            },
            {
                "id":"2531",
                "name":"卫生和社会工作",
                "count":9307
            },
            {
                "id":"2439",
                "name":"采矿业",
                "count":8497
            },
            {
                "id":"2525",
                "name":"居民服务、修理和其他服务业",
                "count":7758
            },
            {
                "id":"2500",
                "name":"住宿和餐饮业",
                "count":4661
            },
            {
                "id":"2540",
                "name":"综合",
                "count":1753
            }
        ],
        "id":1,
        "showname":"行业",
        "multiValued":true
    },
    {
        "type":"company",
        "item":[
            {
                "id":null,
                "name":"高盛",
                "count":7948
            },
            {
                "id":null,
                "name":"阳光城",
                "count":6278
            },
            {
                "id":null,
                "name":"Credit Suisse Ag Credit Suisse X-Links",
                "count":6114
            },
            {
                "id":null,
                "name":"摩根大通",
                "count":6025
            },
            {
                "id":null,
                "name":"晨鸣纸业",
                "count":5834
            },
            {
                "id":null,
                "name":"怡亚通",
                "count":5775
            },
            {
                "id":null,
                "name":"广发证券",
                "count":5394
            },
            {
                "id":null,
                "name":"中泰化学",
                "count":5319
            },
            {
                "id":null,
                "name":"渤海租赁",
                "count":5140
            },
            {
                "id":null,
                "name":"金科股份",
                "count":5098
            },
            {
                "id":null,
                "name":"中兴通讯",
                "count":5098
            },
            {
                "id":null,
                "name":"海信家电",
                "count":4945
            },
            {
                "id":null,
                "name":"TCL集团",
                "count":4939
            },
            {
                "id":null,
                "name":"泰禾集团",
                "count":4916
            },
            {
                "id":null,
                "name":"泛海控股",
                "count":4815
            },
            {
                "id":null,
                "name":"中交地产",
                "count":4743
            },
            {
                "id":null,
                "name":"神州信息",
                "count":4687
            },
            {
                "id":null,
                "name":"科陆电子",
                "count":4603
            },
            {
                "id":null,
                "name":"高鸿股份",
                "count":4600
            },
            {
                "id":null,
                "name":"Northern Trust Corp Series C Pfd",
                "count":4572
            },
            {
                "id":null,
                "name":"*ST华泽",
                "count":4536
            },
            {
                "id":null,
                "name":"东江环保",
                "count":4506
            },
            {
                "id":null,
                "name":"平潭发展",
                "count":4449
            },
            {
                "id":null,
                "name":"中联重科",
                "count":4437
            },
            {
                "id":null,
                "name":"复星医药",
                "count":4394
            },
            {
                "id":null,
                "name":"启迪桑德",
                "count":4376
            },
            {
                "id":null,
                "name":"华映科技",
                "count":4358
            },
            {
                "id":null,
                "name":"ST冠福",
                "count":4323
            },
            {
                "id":null,
                "name":"中国铝业",
                "count":4317
            },
            {
                "id":null,
                "name":"中关村",
                "count":4278
            },
            {
                "id":null,
                "name":"中弘退",
                "count":4277
            },
            {
                "id":null,
                "name":"银亿股份",
                "count":4234
            },
            {
                "id":null,
                "name":"鸿达兴业",
                "count":4204
            },
            {
                "id":null,
                "name":"吉电股份",
                "count":4202
            },
            {
                "id":null,
                "name":"美丽生态",
                "count":4171
            },
            {
                "id":null,
                "name":"全新好",
                "count":4164
            },
            {
                "id":null,
                "name":"恒逸石化",
                "count":4146
            },
            {
                "id":null,
                "name":"金风科技",
                "count":4142
            },
            {
                "id":null,
                "name":"利欧股份",
                "count":4125
            },
            {
                "id":null,
                "name":"荣盛发展",
                "count":4124
            },
            {
                "id":null,
                "name":"苏宁易购",
                "count":4089
            },
            {
                "id":null,
                "name":"京东方A",
                "count":4085
            },
            {
                "id":null,
                "name":"中环股份",
                "count":4074
            },
            {
                "id":null,
                "name":"北京文化",
                "count":4073
            },
            {
                "id":null,
                "name":"中南建设",
                "count":4073
            },
            {
                "id":null,
                "name":"中天金融",
                "count":4055
            },
            {
                "id":null,
                "name":"LendingClub Corp",
                "count":4046
            },
            {
                "id":null,
                "name":"*ST凯迪",
                "count":4044
            },
            {
                "id":null,
                "name":"众合科技",
                "count":4042
            },
            {
                "id":null,
                "name":"汇丰控股",
                "count":4033
            },
            {
                "id":null,
                "name":"中集集团",
                "count":4022
            },
            {
                "id":null,
                "name":"东旭光电",
                "count":4022
            },
            {
                "id":null,
                "name":"华菱钢铁",
                "count":4008
            },
            {
                "id":null,
                "name":"黑芝麻",
                "count":3967
            },
            {
                "id":null,
                "name":"华数传媒",
                "count":3957
            },
            {
                "id":null,
                "name":"神州数码",
                "count":3953
            },
            {
                "id":null,
                "name":"正邦科技",
                "count":3943
            },
            {
                "id":null,
                "name":"*ST中绒",
                "count":3941
            },
            {
                "id":null,
                "name":"远兴能源",
                "count":3898
            },
            {
                "id":null,
                "name":"*ST云网",
                "count":3895
            },
            {
                "id":null,
                "name":"东方园林",
                "count":3853
            },
            {
                "id":null,
                "name":"惠程科技",
                "count":3850
            },
            {
                "id":null,
                "name":"新华联",
                "count":3834
            },
            {
                "id":null,
                "name":"京蓝科技",
                "count":3816
            },
            {
                "id":null,
                "name":"欢瑞世纪",
                "count":3813
            },
            {
                "id":null,
                "name":"美好置业",
                "count":3812
            },
            {
                "id":null,
                "name":"中国长城",
                "count":3812
            },
            {
                "id":null,
                "name":"中捷资源",
                "count":3811
            },
            {
                "id":null,
                "name":"海南海药",
                "count":3798
            },
            {
                "id":null,
                "name":"加拿大皇家银行",
                "count":3785
            },
            {
                "id":null,
                "name":"中核钛白",
                "count":3778
            },
            {
                "id":null,
                "name":"振兴生化",
                "count":3774
            },
            {
                "id":null,
                "name":"云南能投",
                "count":3774
            },
            {
                "id":null,
                "name":"*ST东凌",
                "count":3768
            },
            {
                "id":null,
                "name":"国海证券",
                "count":3765
            },
            {
                "id":null,
                "name":"沃尔核材",
                "count":3764
            },
            {
                "id":null,
                "name":"中航飞机",
                "count":3742
            },
            {
                "id":null,
                "name":"华邦健康",
                "count":3740
            },
            {
                "id":null,
                "name":"华闻传媒",
                "count":3735
            },
            {
                "id":null,
                "name":"视觉中国",
                "count":3734
            },
            {
                "id":null,
                "name":"万泽股份",
                "count":3725
            },
            {
                "id":null,
                "name":"徐工机械",
                "count":3722
            },
            {
                "id":null,
                "name":"华塑控股",
                "count":3720
            },
            {
                "id":null,
                "name":"宜华健康",
                "count":3713
            },
            {
                "id":null,
                "name":"协鑫集成",
                "count":3709
            },
            {
                "id":null,
                "name":"*ST宜化",
                "count":3702
            },
            {
                "id":null,
                "name":"三湘印象",
                "count":3700
            },
            {
                "id":null,
                "name":"华天酒店",
                "count":3687
            },
            {
                "id":null,
                "name":"花旗集团",
                "count":3683
            },
            {
                "id":null,
                "name":"国元证券",
                "count":3674
            },
            {
                "id":null,
                "name":"深大通",
                "count":3668
            },
            {
                "id":null,
                "name":"云南铜业",
                "count":3666
            },
            {
                "id":null,
                "name":"恒天海龙",
                "count":3665
            },
            {
                "id":null,
                "name":"供销大集",
                "count":3665
            },
            {
                "id":null,
                "name":"瑞银集团",
                "count":3664
            },
            {
                "id":null,
                "name":"粤水电",
                "count":3656
            },
            {
                "id":null,
                "name":"海航投资",
                "count":3654
            },
            {
                "id":null,
                "name":"蓝色光标",
                "count":3650
            },
            {
                "id":null,
                "name":"格林美",
                "count":3637
            },
            {
                "id":null,
                "name":"*ST地矿",
                "count":3628
            },
            {
                "id":null,
                "name":"自选股",
                "count":null
            }
        ],
        "id":2,
        "showname":"公司",
        "multiValued":true
    },
    {
        "type":"categoryIds",
        "item":[
            {
                "id":"F004",
                "name":"沪深股公告",
                "count":4545476
            },
            {
                "id":"F009",
                "name":"美股公告",
                "count":3350480
            },
            {
                "id":"F013",
                "name":"股转系统公告",
                "count":1659281
            },
            {
                "id":"F008",
                "name":"港股公告",
                "count":1328767
            },
            {
                "id":"F005",
                "name":"基金公告",
                "count":818720
            },
            {
                "id":"F006",
                "name":"债券公告",
                "count":354143
            },
            {
                "id":"F007",
                "name":"理财公告",
                "count":314466
            },
            {
                "id":"F015",
                "name":"交易所公告",
                "count":42560
            },
            {
                "id":"F017",
                "name":"法律规范",
                "count":29839
            },
            {
                "id":"F016",
                "name":"会议路演",
                "count":5492
            },
            {
                "id":"F014",
                "name":"期权公告",
                "count":400
            }
        ],
        "id":3,
        "showname":"分类",
        "multiValued":true
    },
    {
        "type":"tags",
        "item":[
            {
                "id":null,
                "name":"利好",
                "count":173307
            },
            {
                "id":null,
                "name":"利空",
                "count":53075
            },
            {
                "id":null,
                "name":"业绩预增",
                "count":29018
            },
            {
                "id":null,
                "name":"业绩预减",
                "count":19102
            },
            {
                "id":null,
                "name":"业绩增",
                "count":11440
            },
            {
                "id":null,
                "name":"业绩减",
                "count":8792
            },
            {
                "id":null,
                "name":"持平",
                "count":14
            }
        ],
        "id":4,
        "showname":"标签",
        "multiValued":true
    },
    {
        "type":"file_type",
        "item":[
            {
                "id":null,
                "name":"pdf",
                "count":10592459
            },
            {
                "id":null,
                "name":"网页",
                "count":5441713
            },
            {
                "id":null,
                "name":"Word",
                "count":306794
            },
            {
                "id":null,
                "name":"Excel",
                "count":94478
            },
            {
                "id":null,
                "name":"压缩包",
                "count":577
            },
            {
                "id":null,
                "name":"ppt",
                "count":137
            }
        ],
        "id":5,
        "showname":"格式",
        "multiValued":true
    },
    {
        "type":"page_count",
        "item":[
            {
                "id":null,
                "name":"10页以下",
                "count":13823996
            },
            {
                "id":null,
                "name":"20页以上",
                "count":1791423
            },
            {
                "id":null,
                "name":"10~20页",
                "count":1170344
            }
        ],
        "id":6,
        "showname":"页数",
        "multiValued":true
    },
    {
        "type":"time_area",
        "item":[
            {
                "id":null,
                "name":"一年内",
                "count":1977580
            },
            {
                "id":null,
                "name":"半年内",
                "count":803540
            },
            {
                "id":null,
                "name":"一季度内",
                "count":398565
            },
            {
                "id":null,
                "name":"一个月内",
                "count":191555
            },
            {
                "id":null,
                "name":"一周内",
                "count":25615
            },
            {
                "id":null,
                "name":"24小时内",
                "count":4101
            }
        ],
        "id":7,
        "showname":"时间",
        "multiValued":false
    }
]